// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Agumon   action size: 36px (auto (normal poses + pad, clamped to [16,64]))   profile size: 29px (auto (native))   pad: 0.12
#ifndef AGUMON_SPRITES_H
#define AGUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define AGUMON_SPRITE_SIZE   36
#define AGUMON_PROFILE_SIZE  29
// Attack frames use their OWN box (bigger than the pose square).
#define AGUMON_ATTACK_W      41
#define AGUMON_ATTACK_H      48

extern const uint16_t agumon_attack_0[] PROGMEM;
extern const uint16_t agumon_attack_1[] PROGMEM;
extern const uint16_t agumon_attack_2[] PROGMEM;
extern const uint16_t agumon_attack_3[] PROGMEM;
extern const uint16_t agumon_attack_4[] PROGMEM;
extern const uint16_t agumon_happy_0[] PROGMEM;
extern const uint16_t agumon_happy_1[] PROGMEM;
extern const uint16_t agumon_happy_2[] PROGMEM;
extern const uint16_t agumon_profile[] PROGMEM;
extern const uint16_t agumon_walk_0[] PROGMEM;
extern const uint16_t agumon_walk_1[] PROGMEM;
extern const uint16_t agumon_walk_2[] PROGMEM;
extern const uint16_t agumon_walkback_0[] PROGMEM;
extern const uint16_t agumon_walkback_1[] PROGMEM;
extern const uint16_t agumon_walkback_2[] PROGMEM;

extern const uint16_t* const agumon_attack_frames[5];
extern const uint16_t* const agumon_happy_frames[3];
extern const uint16_t* const agumon_walk_frames[3];
extern const uint16_t* const agumon_walkback_frames[3];

#endif
