// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Armadillomon   action size: 35px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef ARMADILLOMON_SPRITES_H
#define ARMADILLOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define ARMADILLOMON_SPRITE_SIZE   35
#define ARMADILLOMON_PROFILE_SIZE  30
// Attack frames use their OWN box (bigger than the pose square).
#define ARMADILLOMON_ATTACK_W      48
#define ARMADILLOMON_ATTACK_H      39

extern const uint16_t armadillomon_attack_0[] PROGMEM;
extern const uint16_t armadillomon_attack_1[] PROGMEM;
extern const uint16_t armadillomon_attack_2[] PROGMEM;
extern const uint16_t armadillomon_happy_0[] PROGMEM;
extern const uint16_t armadillomon_happy_1[] PROGMEM;
extern const uint16_t armadillomon_happy_2[] PROGMEM;
extern const uint16_t armadillomon_profile[] PROGMEM;
extern const uint16_t armadillomon_walk_0[] PROGMEM;
extern const uint16_t armadillomon_walk_1[] PROGMEM;
extern const uint16_t armadillomon_walk_2[] PROGMEM;
extern const uint16_t armadillomon_walkback_0[] PROGMEM;
extern const uint16_t armadillomon_walkback_1[] PROGMEM;
extern const uint16_t armadillomon_walkback_2[] PROGMEM;

extern const uint16_t* const armadillomon_attack_frames[3];
extern const uint16_t* const armadillomon_happy_frames[3];
extern const uint16_t* const armadillomon_walk_frames[3];
extern const uint16_t* const armadillomon_walkback_frames[3];

#endif
