// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Aruraumon   action size: 40px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef ARURAUMON_SPRITES_H
#define ARURAUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define ARURAUMON_SPRITE_SIZE   40
#define ARURAUMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define ARURAUMON_ATTACK_W      44
#define ARURAUMON_ATTACK_H      48

extern const uint16_t aruraumon_attack_0[] PROGMEM;
extern const uint16_t aruraumon_attack_1[] PROGMEM;
extern const uint16_t aruraumon_attack_2[] PROGMEM;
extern const uint16_t aruraumon_happy_0[] PROGMEM;
extern const uint16_t aruraumon_happy_1[] PROGMEM;
extern const uint16_t aruraumon_happy_2[] PROGMEM;
extern const uint16_t aruraumon_profile[] PROGMEM;
extern const uint16_t aruraumon_walk_0[] PROGMEM;
extern const uint16_t aruraumon_walk_1[] PROGMEM;
extern const uint16_t aruraumon_walk_2[] PROGMEM;
extern const uint16_t aruraumon_walkback_0[] PROGMEM;
extern const uint16_t aruraumon_walkback_1[] PROGMEM;
extern const uint16_t aruraumon_walkback_2[] PROGMEM;

extern const uint16_t* const aruraumon_attack_frames[3];
extern const uint16_t* const aruraumon_happy_frames[3];
extern const uint16_t* const aruraumon_walk_frames[3];
extern const uint16_t* const aruraumon_walkback_frames[3];

#endif
