// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Betamon   action size: 40px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef BETAMON_SPRITES_H
#define BETAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define BETAMON_SPRITE_SIZE   40
#define BETAMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define BETAMON_ATTACK_W      48
#define BETAMON_ATTACK_H      43

extern const uint16_t betamon_attack_0[] PROGMEM;
extern const uint16_t betamon_attack_1[] PROGMEM;
extern const uint16_t betamon_attack_2[] PROGMEM;
extern const uint16_t betamon_attack_3[] PROGMEM;
extern const uint16_t betamon_happy_0[] PROGMEM;
extern const uint16_t betamon_happy_1[] PROGMEM;
extern const uint16_t betamon_happy_2[] PROGMEM;
extern const uint16_t betamon_profile[] PROGMEM;
extern const uint16_t betamon_walk_0[] PROGMEM;
extern const uint16_t betamon_walk_1[] PROGMEM;
extern const uint16_t betamon_walk_2[] PROGMEM;
extern const uint16_t betamon_walkback_0[] PROGMEM;
extern const uint16_t betamon_walkback_1[] PROGMEM;
extern const uint16_t betamon_walkback_2[] PROGMEM;

extern const uint16_t* const betamon_attack_frames[4];
extern const uint16_t* const betamon_happy_frames[3];
extern const uint16_t* const betamon_walk_frames[3];
extern const uint16_t* const betamon_walkback_frames[3];

#endif
