// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Biyomon   action size: 37px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef BIYOMON_SPRITES_H
#define BIYOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define BIYOMON_SPRITE_SIZE   37
#define BIYOMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define BIYOMON_ATTACK_W      48
#define BIYOMON_ATTACK_H      45

extern const uint16_t biyomon_attack_0[] PROGMEM;
extern const uint16_t biyomon_attack_1[] PROGMEM;
extern const uint16_t biyomon_attack_2[] PROGMEM;
extern const uint16_t biyomon_happy_0[] PROGMEM;
extern const uint16_t biyomon_happy_1[] PROGMEM;
extern const uint16_t biyomon_happy_2[] PROGMEM;
extern const uint16_t biyomon_profile[] PROGMEM;
extern const uint16_t biyomon_walk_0[] PROGMEM;
extern const uint16_t biyomon_walk_1[] PROGMEM;
extern const uint16_t biyomon_walk_2[] PROGMEM;
extern const uint16_t biyomon_walkback_0[] PROGMEM;
extern const uint16_t biyomon_walkback_1[] PROGMEM;
extern const uint16_t biyomon_walkback_2[] PROGMEM;

extern const uint16_t* const biyomon_attack_frames[3];
extern const uint16_t* const biyomon_happy_frames[3];
extern const uint16_t* const biyomon_walk_frames[3];
extern const uint16_t* const biyomon_walkback_frames[3];

#endif
