// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: chibomon   action size: 32px (auto-derived (clamped to [32,56]))   profile size: 30px   pad: 0.12
#ifndef CHIBOMON_SPRITES_H
#define CHIBOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define CHIBOMON_SPRITE_SIZE   32
#define CHIBOMON_PROFILE_SIZE  30

extern const uint16_t chibomon_happy_0[] PROGMEM;
extern const uint16_t chibomon_happy_1[] PROGMEM;
extern const uint16_t chibomon_happy_2[] PROGMEM;
extern const uint16_t chibomon_profile[] PROGMEM;
extern const uint16_t chibomon_walk_0[] PROGMEM;
extern const uint16_t chibomon_walk_1[] PROGMEM;
extern const uint16_t chibomon_walk_2[] PROGMEM;
extern const uint16_t chibomon_walkback_0[] PROGMEM;
extern const uint16_t chibomon_walkback_1[] PROGMEM;
extern const uint16_t chibomon_walkback_2[] PROGMEM;

extern const uint16_t* const chibomon_happy_frames[3];
extern const uint16_t* const chibomon_walk_frames[3];
extern const uint16_t* const chibomon_walkback_frames[3];

#endif
