// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: DemiDevimon   action size: 33px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef DEMIDEVIMON_SPRITES_H
#define DEMIDEVIMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define DEMIDEVIMON_SPRITE_SIZE   33
#define DEMIDEVIMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define DEMIDEVIMON_ATTACK_W      48
#define DEMIDEVIMON_ATTACK_H      37

extern const uint16_t demidevimon_attack_0[] PROGMEM;
extern const uint16_t demidevimon_attack_1[] PROGMEM;
extern const uint16_t demidevimon_attack_2[] PROGMEM;
extern const uint16_t demidevimon_attack_3[] PROGMEM;
extern const uint16_t demidevimon_happy_0[] PROGMEM;
extern const uint16_t demidevimon_happy_1[] PROGMEM;
extern const uint16_t demidevimon_happy_2[] PROGMEM;
extern const uint16_t demidevimon_profile[] PROGMEM;
extern const uint16_t demidevimon_walk_0[] PROGMEM;
extern const uint16_t demidevimon_walk_1[] PROGMEM;
extern const uint16_t demidevimon_walk_2[] PROGMEM;
extern const uint16_t demidevimon_walkback_0[] PROGMEM;
extern const uint16_t demidevimon_walkback_1[] PROGMEM;
extern const uint16_t demidevimon_walkback_2[] PROGMEM;

extern const uint16_t* const demidevimon_attack_frames[4];
extern const uint16_t* const demidevimon_happy_frames[3];
extern const uint16_t* const demidevimon_walk_frames[3];
extern const uint16_t* const demidevimon_walkback_frames[3];

#endif
