// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: dorimon   action size: 36px (auto-derived (clamped to [32,56]))   profile size: 30px   pad: 0.12
#ifndef DORIMON_SPRITES_H
#define DORIMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define DORIMON_SPRITE_SIZE   36
#define DORIMON_PROFILE_SIZE  30

extern const uint16_t dorimon_attack_0[] PROGMEM;
extern const uint16_t dorimon_attack_1[] PROGMEM;
extern const uint16_t dorimon_attack_2[] PROGMEM;
extern const uint16_t dorimon_attack_3[] PROGMEM;
extern const uint16_t dorimon_happy_0[] PROGMEM;
extern const uint16_t dorimon_happy_1[] PROGMEM;
extern const uint16_t dorimon_happy_2[] PROGMEM;
extern const uint16_t dorimon_profile[] PROGMEM;
extern const uint16_t dorimon_walk_0[] PROGMEM;
extern const uint16_t dorimon_walk_1[] PROGMEM;
extern const uint16_t dorimon_walk_2[] PROGMEM;
extern const uint16_t dorimon_walkback_0[] PROGMEM;
extern const uint16_t dorimon_walkback_1[] PROGMEM;
extern const uint16_t dorimon_walkback_2[] PROGMEM;

extern const uint16_t* const dorimon_attack_frames[4];
extern const uint16_t* const dorimon_happy_frames[3];
extern const uint16_t* const dorimon_walk_frames[3];
extern const uint16_t* const dorimon_walkback_frames[3];

#endif
