// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Dorumon   action size: 41px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef DORUMON_SPRITES_H
#define DORUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define DORUMON_SPRITE_SIZE   41
#define DORUMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define DORUMON_ATTACK_W      42
#define DORUMON_ATTACK_H      48

extern const uint16_t dorumon_attack_0[] PROGMEM;
extern const uint16_t dorumon_attack_1[] PROGMEM;
extern const uint16_t dorumon_attack_2[] PROGMEM;
extern const uint16_t dorumon_happy_0[] PROGMEM;
extern const uint16_t dorumon_happy_1[] PROGMEM;
extern const uint16_t dorumon_happy_2[] PROGMEM;
extern const uint16_t dorumon_profile[] PROGMEM;
extern const uint16_t dorumon_walk_0[] PROGMEM;
extern const uint16_t dorumon_walk_1[] PROGMEM;
extern const uint16_t dorumon_walk_2[] PROGMEM;
extern const uint16_t dorumon_walkback_0[] PROGMEM;
extern const uint16_t dorumon_walkback_1[] PROGMEM;
extern const uint16_t dorumon_walkback_2[] PROGMEM;

extern const uint16_t* const dorumon_attack_frames[3];
extern const uint16_t* const dorumon_happy_frames[3];
extern const uint16_t* const dorumon_walk_frames[3];
extern const uint16_t* const dorumon_walkback_frames[3];

#endif
