// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Floramon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 27px (auto (native))   pad: 0.12
#ifndef FLORAMON_SPRITES_H
#define FLORAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define FLORAMON_SPRITE_SIZE   43
#define FLORAMON_PROFILE_SIZE  27
// Attack frames use their OWN box (bigger than the pose square).
#define FLORAMON_ATTACK_W      48
#define FLORAMON_ATTACK_H      43

extern const uint16_t floramon_attack_0[] PROGMEM;
extern const uint16_t floramon_attack_1[] PROGMEM;
extern const uint16_t floramon_attack_2[] PROGMEM;
extern const uint16_t floramon_happy_0[] PROGMEM;
extern const uint16_t floramon_happy_1[] PROGMEM;
extern const uint16_t floramon_happy_2[] PROGMEM;
extern const uint16_t floramon_profile[] PROGMEM;
extern const uint16_t floramon_walk_0[] PROGMEM;
extern const uint16_t floramon_walk_1[] PROGMEM;
extern const uint16_t floramon_walk_2[] PROGMEM;
extern const uint16_t floramon_walkback_0[] PROGMEM;
extern const uint16_t floramon_walkback_1[] PROGMEM;
extern const uint16_t floramon_walkback_2[] PROGMEM;

extern const uint16_t* const floramon_attack_frames[3];
extern const uint16_t* const floramon_happy_frames[3];
extern const uint16_t* const floramon_walk_frames[3];
extern const uint16_t* const floramon_walkback_frames[3];

#endif
