// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Gabumon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef GABUMON_SPRITES_H
#define GABUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define GABUMON_SPRITE_SIZE   43
#define GABUMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define GABUMON_ATTACK_W      48
#define GABUMON_ATTACK_H      41

extern const uint16_t gabumon_attack_0[] PROGMEM;
extern const uint16_t gabumon_attack_1[] PROGMEM;
extern const uint16_t gabumon_attack_2[] PROGMEM;
extern const uint16_t gabumon_happy_0[] PROGMEM;
extern const uint16_t gabumon_happy_1[] PROGMEM;
extern const uint16_t gabumon_happy_2[] PROGMEM;
extern const uint16_t gabumon_profile[] PROGMEM;
extern const uint16_t gabumon_walk_0[] PROGMEM;
extern const uint16_t gabumon_walk_1[] PROGMEM;
extern const uint16_t gabumon_walk_2[] PROGMEM;
extern const uint16_t gabumon_walkback_0[] PROGMEM;
extern const uint16_t gabumon_walkback_1[] PROGMEM;
extern const uint16_t gabumon_walkback_2[] PROGMEM;

extern const uint16_t* const gabumon_attack_frames[3];
extern const uint16_t* const gabumon_happy_frames[3];
extern const uint16_t* const gabumon_walk_frames[3];
extern const uint16_t* const gabumon_walkback_frames[3];

#endif
