// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Gaomon   action size: 41px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef GAOMON_SPRITES_H
#define GAOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define GAOMON_SPRITE_SIZE   41
#define GAOMON_PROFILE_SIZE  30
// Attack frames use their OWN box (bigger than the pose square).
#define GAOMON_ATTACK_W      42
#define GAOMON_ATTACK_H      48

extern const uint16_t gaomon_attack_0[] PROGMEM;
extern const uint16_t gaomon_attack_1[] PROGMEM;
extern const uint16_t gaomon_attack_2[] PROGMEM;
extern const uint16_t gaomon_happy_0[] PROGMEM;
extern const uint16_t gaomon_happy_1[] PROGMEM;
extern const uint16_t gaomon_profile[] PROGMEM;
extern const uint16_t gaomon_walk_0[] PROGMEM;
extern const uint16_t gaomon_walk_1[] PROGMEM;
extern const uint16_t gaomon_walk_2[] PROGMEM;
extern const uint16_t gaomon_walkback_0[] PROGMEM;
extern const uint16_t gaomon_walkback_1[] PROGMEM;
extern const uint16_t gaomon_walkback_2[] PROGMEM;

extern const uint16_t* const gaomon_attack_frames[3];
extern const uint16_t* const gaomon_happy_frames[2];
extern const uint16_t* const gaomon_walk_frames[3];
extern const uint16_t* const gaomon_walkback_frames[3];

#endif
