// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: gargomon   action size: 50px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef GARGOMON_SPRITES_H
#define GARGOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define GARGOMON_SPRITE_SIZE   50
#define GARGOMON_PROFILE_SIZE  30

extern const uint16_t gargomon_happy_0[] PROGMEM;
extern const uint16_t gargomon_happy_1[] PROGMEM;
extern const uint16_t gargomon_happy_2[] PROGMEM;
extern const uint16_t gargomon_profile[] PROGMEM;
extern const uint16_t gargomon_walk_0[] PROGMEM;
extern const uint16_t gargomon_walk_1[] PROGMEM;
extern const uint16_t gargomon_walk_2[] PROGMEM;
extern const uint16_t gargomon_walkback_0[] PROGMEM;
extern const uint16_t gargomon_walkback_1[] PROGMEM;
extern const uint16_t gargomon_walkback_2[] PROGMEM;

extern const uint16_t* const gargomon_happy_frames[3];
extern const uint16_t* const gargomon_walk_frames[4];
extern const uint16_t* const gargomon_walkback_frames[4];

#endif
