// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Goburimon   action size: 53px (auto (normal poses + pad, clamped to [16,64]))   profile size: 29px (auto (native))   pad: 0.12
#ifndef GOBURIMON_SPRITES_H
#define GOBURIMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define GOBURIMON_SPRITE_SIZE   53
#define GOBURIMON_PROFILE_SIZE  29
// Attack frames use their OWN box (bigger than the pose square).
#define GOBURIMON_ATTACK_W      48
#define GOBURIMON_ATTACK_H      44

extern const uint16_t goburimon_attack_0[] PROGMEM;
extern const uint16_t goburimon_attack_1[] PROGMEM;
extern const uint16_t goburimon_attack_2[] PROGMEM;
extern const uint16_t goburimon_happy_0[] PROGMEM;
extern const uint16_t goburimon_happy_1[] PROGMEM;
extern const uint16_t goburimon_happy_2[] PROGMEM;
extern const uint16_t goburimon_profile[] PROGMEM;
extern const uint16_t goburimon_walk_0[] PROGMEM;
extern const uint16_t goburimon_walk_1[] PROGMEM;
extern const uint16_t goburimon_walk_2[] PROGMEM;
extern const uint16_t goburimon_walkback_0[] PROGMEM;
extern const uint16_t goburimon_walkback_1[] PROGMEM;
extern const uint16_t goburimon_walkback_2[] PROGMEM;

extern const uint16_t* const goburimon_attack_frames[3];
extern const uint16_t* const goburimon_happy_frames[3];
extern const uint16_t* const goburimon_walk_frames[3];
extern const uint16_t* const goburimon_walkback_frames[3];

#endif
