// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Gotsumon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef GOTSUMON_SPRITES_H
#define GOTSUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define GOTSUMON_SPRITE_SIZE   43
#define GOTSUMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define GOTSUMON_ATTACK_W      48
#define GOTSUMON_ATTACK_H      48

extern const uint16_t gotsumon_attack_0[] PROGMEM;
extern const uint16_t gotsumon_attack_1[] PROGMEM;
extern const uint16_t gotsumon_attack_2[] PROGMEM;
extern const uint16_t gotsumon_happy_0[] PROGMEM;
extern const uint16_t gotsumon_happy_1[] PROGMEM;
extern const uint16_t gotsumon_happy_2[] PROGMEM;
extern const uint16_t gotsumon_profile[] PROGMEM;
extern const uint16_t gotsumon_walk_0[] PROGMEM;
extern const uint16_t gotsumon_walk_1[] PROGMEM;
extern const uint16_t gotsumon_walk_2[] PROGMEM;
extern const uint16_t gotsumon_walkback_0[] PROGMEM;
extern const uint16_t gotsumon_walkback_1[] PROGMEM;
extern const uint16_t gotsumon_walkback_2[] PROGMEM;

extern const uint16_t* const gotsumon_attack_frames[3];
extern const uint16_t* const gotsumon_happy_frames[3];
extern const uint16_t* const gotsumon_walk_frames[3];
extern const uint16_t* const gotsumon_walkback_frames[3];

#endif
