// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Guilmon   action size: 41px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef GUILMON_SPRITES_H
#define GUILMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define GUILMON_SPRITE_SIZE   41
// Attack frames use their OWN box (bigger than the pose square).
#define GUILMON_ATTACK_W      48
#define GUILMON_ATTACK_H      48

extern const uint16_t guilmon_attack_0[] PROGMEM;
extern const uint16_t guilmon_attack_1[] PROGMEM;
extern const uint16_t guilmon_attack_2[] PROGMEM;
extern const uint16_t guilmon_walk_0[] PROGMEM;
extern const uint16_t guilmon_walk_1[] PROGMEM;
extern const uint16_t guilmon_walk_2[] PROGMEM;
extern const uint16_t guilmon_walk_3[] PROGMEM;
extern const uint16_t guilmon_walkback_0[] PROGMEM;
extern const uint16_t guilmon_walkback_1[] PROGMEM;
extern const uint16_t guilmon_walkback_2[] PROGMEM;
extern const uint16_t guilmon_walkback_3[] PROGMEM;

extern const uint16_t* const guilmon_attack_frames[3];
extern const uint16_t* const guilmon_walk_frames[4];
extern const uint16_t* const guilmon_walkback_frames[4];

#endif
