// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Hawkmon   action size: 39px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef HAWKMON_SPRITES_H
#define HAWKMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define HAWKMON_SPRITE_SIZE   39
#define HAWKMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define HAWKMON_ATTACK_W      47
#define HAWKMON_ATTACK_H      48

extern const uint16_t hawkmon_attack_0[] PROGMEM;
extern const uint16_t hawkmon_attack_1[] PROGMEM;
extern const uint16_t hawkmon_attack_2[] PROGMEM;
extern const uint16_t hawkmon_happy_0[] PROGMEM;
extern const uint16_t hawkmon_happy_1[] PROGMEM;
extern const uint16_t hawkmon_happy_2[] PROGMEM;
extern const uint16_t hawkmon_profile[] PROGMEM;
extern const uint16_t hawkmon_walk_0[] PROGMEM;
extern const uint16_t hawkmon_walk_1[] PROGMEM;
extern const uint16_t hawkmon_walk_2[] PROGMEM;
extern const uint16_t hawkmon_walkback_0[] PROGMEM;
extern const uint16_t hawkmon_walkback_1[] PROGMEM;
extern const uint16_t hawkmon_walkback_2[] PROGMEM;

extern const uint16_t* const hawkmon_attack_frames[3];
extern const uint16_t* const hawkmon_happy_frames[3];
extern const uint16_t* const hawkmon_walk_frames[3];
extern const uint16_t* const hawkmon_walkback_frames[3];

#endif
