// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Impmon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 27px (auto (native))   pad: 0.12
#ifndef IMPMON_SPRITES_H
#define IMPMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define IMPMON_SPRITE_SIZE   43
#define IMPMON_PROFILE_SIZE  27
// Attack frames use their OWN box (bigger than the pose square).
#define IMPMON_ATTACK_W      39
#define IMPMON_ATTACK_H      48

extern const uint16_t impmon_attack_0[] PROGMEM;
extern const uint16_t impmon_attack_1[] PROGMEM;
extern const uint16_t impmon_attack_2[] PROGMEM;
extern const uint16_t impmon_happy_0[] PROGMEM;
extern const uint16_t impmon_happy_1[] PROGMEM;
extern const uint16_t impmon_happy_2[] PROGMEM;
extern const uint16_t impmon_profile[] PROGMEM;
extern const uint16_t impmon_walk_0[] PROGMEM;
extern const uint16_t impmon_walk_1[] PROGMEM;
extern const uint16_t impmon_walk_2[] PROGMEM;
extern const uint16_t impmon_walkback_0[] PROGMEM;
extern const uint16_t impmon_walkback_1[] PROGMEM;
extern const uint16_t impmon_walkback_2[] PROGMEM;

extern const uint16_t* const impmon_attack_frames[3];
extern const uint16_t* const impmon_happy_frames[3];
extern const uint16_t* const impmon_walk_frames[3];
extern const uint16_t* const impmon_walkback_frames[3];

#endif
