// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: kapurimon   action size: 24px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef KAPURIMON_SPRITES_H
#define KAPURIMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define KAPURIMON_SPRITE_SIZE   24
#define KAPURIMON_PROFILE_SIZE  30

extern const uint16_t kapurimon_attack_0[] PROGMEM;
extern const uint16_t kapurimon_attack_1[] PROGMEM;
extern const uint16_t kapurimon_attack_2[] PROGMEM;
extern const uint16_t kapurimon_happy_0[] PROGMEM;
extern const uint16_t kapurimon_happy_1[] PROGMEM;
extern const uint16_t kapurimon_happy_2[] PROGMEM;
extern const uint16_t kapurimon_profile[] PROGMEM;
extern const uint16_t kapurimon_walk_0[] PROGMEM;
extern const uint16_t kapurimon_walk_1[] PROGMEM;
extern const uint16_t kapurimon_walk_2[] PROGMEM;
extern const uint16_t kapurimon_walkback_0[] PROGMEM;
extern const uint16_t kapurimon_walkback_1[] PROGMEM;
extern const uint16_t kapurimon_walkback_2[] PROGMEM;

extern const uint16_t* const kapurimon_attack_frames[3];
extern const uint16_t* const kapurimon_happy_frames[3];
extern const uint16_t* const kapurimon_walk_frames[3];
extern const uint16_t* const kapurimon_walkback_frames[3];

#endif
