// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Keramon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef KERAMON_SPRITES_H
#define KERAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define KERAMON_SPRITE_SIZE   43
#define KERAMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define KERAMON_ATTACK_W      34
#define KERAMON_ATTACK_H      48

extern const uint16_t keramon_attack_0[] PROGMEM;
extern const uint16_t keramon_attack_1[] PROGMEM;
extern const uint16_t keramon_attack_2[] PROGMEM;
extern const uint16_t keramon_happy_0[] PROGMEM;
extern const uint16_t keramon_happy_1[] PROGMEM;
extern const uint16_t keramon_happy_2[] PROGMEM;
extern const uint16_t keramon_profile[] PROGMEM;
extern const uint16_t keramon_walk_0[] PROGMEM;
extern const uint16_t keramon_walk_1[] PROGMEM;
extern const uint16_t keramon_walk_2[] PROGMEM;
extern const uint16_t keramon_walkback_0[] PROGMEM;
extern const uint16_t keramon_walkback_1[] PROGMEM;
extern const uint16_t keramon_walkback_2[] PROGMEM;

extern const uint16_t* const keramon_attack_frames[3];
extern const uint16_t* const keramon_happy_frames[3];
extern const uint16_t* const keramon_walk_frames[3];
extern const uint16_t* const keramon_walkback_frames[3];

#endif
