// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: koromon   action size: 20px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef KOROMON_SPRITES_H
#define KOROMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define KOROMON_SPRITE_SIZE   20
#define KOROMON_PROFILE_SIZE  30

extern const uint16_t koromon_attack_0[] PROGMEM;
extern const uint16_t koromon_attack_1[] PROGMEM;
extern const uint16_t koromon_attack_2[] PROGMEM;
extern const uint16_t koromon_attack_3[] PROGMEM;
extern const uint16_t koromon_attack_4[] PROGMEM;
extern const uint16_t koromon_happy_0[] PROGMEM;
extern const uint16_t koromon_happy_1[] PROGMEM;
extern const uint16_t koromon_profile[] PROGMEM;
extern const uint16_t koromon_walk_0[] PROGMEM;
extern const uint16_t koromon_walk_1[] PROGMEM;
extern const uint16_t koromon_walk_2[] PROGMEM;
extern const uint16_t koromon_walkback_0[] PROGMEM;
extern const uint16_t koromon_walkback_1[] PROGMEM;
extern const uint16_t koromon_walkback_2[] PROGMEM;

extern const uint16_t* const koromon_attack_frames[5];
extern const uint16_t* const koromon_happy_frames[2];
extern const uint16_t* const koromon_walk_frames[3];
extern const uint16_t* const koromon_walkback_frames[3];

#endif
