// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Kotemon   action size: 39px (auto (normal poses + pad, clamped to [16,64]))   profile size: 26px (auto (native))   pad: 0.12
#ifndef KOTEMON_SPRITES_H
#define KOTEMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define KOTEMON_SPRITE_SIZE   39
#define KOTEMON_PROFILE_SIZE  26
// Attack frames use their OWN box (bigger than the pose square).
#define KOTEMON_ATTACK_W      41
#define KOTEMON_ATTACK_H      48

extern const uint16_t kotemon_attack_0[] PROGMEM;
extern const uint16_t kotemon_attack_1[] PROGMEM;
extern const uint16_t kotemon_attack_2[] PROGMEM;
extern const uint16_t kotemon_happy_0[] PROGMEM;
extern const uint16_t kotemon_happy_1[] PROGMEM;
extern const uint16_t kotemon_happy_2[] PROGMEM;
extern const uint16_t kotemon_profile[] PROGMEM;
extern const uint16_t kotemon_walk_0[] PROGMEM;
extern const uint16_t kotemon_walk_1[] PROGMEM;
extern const uint16_t kotemon_walk_2[] PROGMEM;
extern const uint16_t kotemon_walkback_0[] PROGMEM;
extern const uint16_t kotemon_walkback_1[] PROGMEM;
extern const uint16_t kotemon_walkback_2[] PROGMEM;

extern const uint16_t* const kotemon_attack_frames[3];
extern const uint16_t* const kotemon_happy_frames[3];
extern const uint16_t* const kotemon_walk_frames[3];
extern const uint16_t* const kotemon_walkback_frames[3];

#endif
