// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Kudamon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 24px (auto (native))   pad: 0.12
#ifndef KUDAMON_SPRITES_H
#define KUDAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define KUDAMON_SPRITE_SIZE   43
#define KUDAMON_PROFILE_SIZE  24
// Attack frames use their OWN box (bigger than the pose square).
#define KUDAMON_ATTACK_W      48
#define KUDAMON_ATTACK_H      41

extern const uint16_t kudamon_attack_0[] PROGMEM;
extern const uint16_t kudamon_attack_1[] PROGMEM;
extern const uint16_t kudamon_attack_2[] PROGMEM;
extern const uint16_t kudamon_happy_0[] PROGMEM;
extern const uint16_t kudamon_happy_1[] PROGMEM;
extern const uint16_t kudamon_happy_2[] PROGMEM;
extern const uint16_t kudamon_profile[] PROGMEM;
extern const uint16_t kudamon_walk_0[] PROGMEM;
extern const uint16_t kudamon_walk_1[] PROGMEM;
extern const uint16_t kudamon_walk_2[] PROGMEM;
extern const uint16_t kudamon_walkback_0[] PROGMEM;
extern const uint16_t kudamon_walkback_1[] PROGMEM;
extern const uint16_t kudamon_walkback_2[] PROGMEM;

extern const uint16_t* const kudamon_attack_frames[3];
extern const uint16_t* const kudamon_happy_frames[3];
extern const uint16_t* const kudamon_walk_frames[3];
extern const uint16_t* const kudamon_walkback_frames[3];

#endif
