// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Kumamon   action size: 37px (auto (normal poses + pad, clamped to [16,64]))   profile size: 27px (auto (native))   pad: 0.12
#ifndef KUMAMON_SPRITES_H
#define KUMAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define KUMAMON_SPRITE_SIZE   37
#define KUMAMON_PROFILE_SIZE  27
// Attack frames use their OWN box (bigger than the pose square).
#define KUMAMON_ATTACK_W      34
#define KUMAMON_ATTACK_H      48

extern const uint16_t kumamon_attack_0[] PROGMEM;
extern const uint16_t kumamon_attack_1[] PROGMEM;
extern const uint16_t kumamon_attack_2[] PROGMEM;
extern const uint16_t kumamon_happy_0[] PROGMEM;
extern const uint16_t kumamon_happy_1[] PROGMEM;
extern const uint16_t kumamon_happy_2[] PROGMEM;
extern const uint16_t kumamon_profile[] PROGMEM;
extern const uint16_t kumamon_walk_0[] PROGMEM;
extern const uint16_t kumamon_walk_1[] PROGMEM;
extern const uint16_t kumamon_walk_2[] PROGMEM;
extern const uint16_t kumamon_walkback_0[] PROGMEM;
extern const uint16_t kumamon_walkback_1[] PROGMEM;
extern const uint16_t kumamon_walkback_2[] PROGMEM;

extern const uint16_t* const kumamon_attack_frames[3];
extern const uint16_t* const kumamon_happy_frames[3];
extern const uint16_t* const kumamon_walk_frames[3];
extern const uint16_t* const kumamon_walkback_frames[3];

#endif
