// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: kuramon   action size: 20px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef KURAMON_SPRITES_H
#define KURAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define KURAMON_SPRITE_SIZE   20
#define KURAMON_PROFILE_SIZE  30

extern const uint16_t kuramon_attack_0[] PROGMEM;
extern const uint16_t kuramon_attack_1[] PROGMEM;
extern const uint16_t kuramon_attack_2[] PROGMEM;
extern const uint16_t kuramon_happy_0[] PROGMEM;
extern const uint16_t kuramon_happy_1[] PROGMEM;
extern const uint16_t kuramon_happy_2[] PROGMEM;
extern const uint16_t kuramon_profile[] PROGMEM;
extern const uint16_t kuramon_walk_0[] PROGMEM;
extern const uint16_t kuramon_walk_1[] PROGMEM;
extern const uint16_t kuramon_walk_2[] PROGMEM;
extern const uint16_t kuramon_walkback_0[] PROGMEM;
extern const uint16_t kuramon_walkback_1[] PROGMEM;
extern const uint16_t kuramon_walkback_2[] PROGMEM;

extern const uint16_t* const kuramon_attack_frames[3];
extern const uint16_t* const kuramon_happy_frames[3];
extern const uint16_t* const kuramon_walk_frames[3];
extern const uint16_t* const kuramon_walkback_frames[3];

#endif
