// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Lalamon   action size: 39px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef LALAMON_SPRITES_H
#define LALAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define LALAMON_SPRITE_SIZE   39
#define LALAMON_PROFILE_SIZE  30
// Attack frames use their OWN box (bigger than the pose square).
#define LALAMON_ATTACK_W      45
#define LALAMON_ATTACK_H      48

extern const uint16_t lalamon_attack_0[] PROGMEM;
extern const uint16_t lalamon_attack_1[] PROGMEM;
extern const uint16_t lalamon_attack_2[] PROGMEM;
extern const uint16_t lalamon_happy_0[] PROGMEM;
extern const uint16_t lalamon_happy_1[] PROGMEM;
extern const uint16_t lalamon_happy_2[] PROGMEM;
extern const uint16_t lalamon_profile[] PROGMEM;
extern const uint16_t lalamon_walk_0[] PROGMEM;
extern const uint16_t lalamon_walk_1[] PROGMEM;
extern const uint16_t lalamon_walk_2[] PROGMEM;
extern const uint16_t lalamon_walkback_0[] PROGMEM;
extern const uint16_t lalamon_walkback_1[] PROGMEM;
extern const uint16_t lalamon_walkback_2[] PROGMEM;

extern const uint16_t* const lalamon_attack_frames[3];
extern const uint16_t* const lalamon_happy_frames[3];
extern const uint16_t* const lalamon_walk_frames[3];
extern const uint16_t* const lalamon_walkback_frames[3];

#endif
