// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Lopmon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef LOPMON_SPRITES_H
#define LOPMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define LOPMON_SPRITE_SIZE   43
#define LOPMON_PROFILE_SIZE  30
// Attack frames use their OWN box (bigger than the pose square).
#define LOPMON_ATTACK_W      48
#define LOPMON_ATTACK_H      25

extern const uint16_t lopmon_attack_0[] PROGMEM;
extern const uint16_t lopmon_attack_1[] PROGMEM;
extern const uint16_t lopmon_attack_2[] PROGMEM;
extern const uint16_t lopmon_happy_0[] PROGMEM;
extern const uint16_t lopmon_happy_1[] PROGMEM;
extern const uint16_t lopmon_happy_2[] PROGMEM;
extern const uint16_t lopmon_profile[] PROGMEM;
extern const uint16_t lopmon_walk_0[] PROGMEM;
extern const uint16_t lopmon_walk_1[] PROGMEM;
extern const uint16_t lopmon_walk_2[] PROGMEM;
extern const uint16_t lopmon_walkback_0[] PROGMEM;
extern const uint16_t lopmon_walkback_1[] PROGMEM;
extern const uint16_t lopmon_walkback_2[] PROGMEM;

extern const uint16_t* const lopmon_attack_frames[3];
extern const uint16_t* const lopmon_happy_frames[3];
extern const uint16_t* const lopmon_walk_frames[3];
extern const uint16_t* const lopmon_walkback_frames[3];

#endif
