// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Muchomon   action size: 39px (auto (normal poses + pad, clamped to [16,64]))   profile size: 27px (auto (native))   pad: 0.12
#ifndef MUCHOMON_SPRITES_H
#define MUCHOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define MUCHOMON_SPRITE_SIZE   39
#define MUCHOMON_PROFILE_SIZE  27
// Attack frames use their OWN box (bigger than the pose square).
#define MUCHOMON_ATTACK_W      48
#define MUCHOMON_ATTACK_H      44

extern const uint16_t muchomon_attack_0[] PROGMEM;
extern const uint16_t muchomon_attack_1[] PROGMEM;
extern const uint16_t muchomon_attack_2[] PROGMEM;
extern const uint16_t muchomon_happy_0[] PROGMEM;
extern const uint16_t muchomon_happy_1[] PROGMEM;
extern const uint16_t muchomon_happy_2[] PROGMEM;
extern const uint16_t muchomon_profile[] PROGMEM;
extern const uint16_t muchomon_walk_0[] PROGMEM;
extern const uint16_t muchomon_walk_1[] PROGMEM;
extern const uint16_t muchomon_walk_2[] PROGMEM;
extern const uint16_t muchomon_walkback_0[] PROGMEM;
extern const uint16_t muchomon_walkback_1[] PROGMEM;
extern const uint16_t muchomon_walkback_2[] PROGMEM;

extern const uint16_t* const muchomon_attack_frames[3];
extern const uint16_t* const muchomon_happy_frames[3];
extern const uint16_t* const muchomon_walk_frames[3];
extern const uint16_t* const muchomon_walkback_frames[3];

#endif
