// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Otamamon   action size: 36px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef OTAMAMON_SPRITES_H
#define OTAMAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define OTAMAMON_SPRITE_SIZE   36
#define OTAMAMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define OTAMAMON_ATTACK_W      48
#define OTAMAMON_ATTACK_H      47

extern const uint16_t otamamon_attack_0[] PROGMEM;
extern const uint16_t otamamon_attack_1[] PROGMEM;
extern const uint16_t otamamon_attack_2[] PROGMEM;
extern const uint16_t otamamon_attack_3[] PROGMEM;
extern const uint16_t otamamon_happy_0[] PROGMEM;
extern const uint16_t otamamon_happy_1[] PROGMEM;
extern const uint16_t otamamon_happy_2[] PROGMEM;
extern const uint16_t otamamon_profile[] PROGMEM;
extern const uint16_t otamamon_walk_0[] PROGMEM;
extern const uint16_t otamamon_walk_1[] PROGMEM;
extern const uint16_t otamamon_walk_2[] PROGMEM;
extern const uint16_t otamamon_walkback_0[] PROGMEM;
extern const uint16_t otamamon_walkback_1[] PROGMEM;
extern const uint16_t otamamon_walkback_2[] PROGMEM;

extern const uint16_t* const otamamon_attack_frames[4];
extern const uint16_t* const otamamon_happy_frames[3];
extern const uint16_t* const otamamon_walk_frames[3];
extern const uint16_t* const otamamon_walkback_frames[3];

#endif
