// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: pagumon   action size: 20px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef PAGUMON_SPRITES_H
#define PAGUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define PAGUMON_SPRITE_SIZE   20
#define PAGUMON_PROFILE_SIZE  30

extern const uint16_t pagumon_attack_0[] PROGMEM;
extern const uint16_t pagumon_attack_1[] PROGMEM;
extern const uint16_t pagumon_attack_2[] PROGMEM;
extern const uint16_t pagumon_attack_3[] PROGMEM;
extern const uint16_t pagumon_attack_4[] PROGMEM;
extern const uint16_t pagumon_happy_0[] PROGMEM;
extern const uint16_t pagumon_happy_1[] PROGMEM;
extern const uint16_t pagumon_happy_2[] PROGMEM;
extern const uint16_t pagumon_profile[] PROGMEM;
extern const uint16_t pagumon_walk_0[] PROGMEM;
extern const uint16_t pagumon_walk_1[] PROGMEM;
extern const uint16_t pagumon_walk_2[] PROGMEM;
extern const uint16_t pagumon_walkback_0[] PROGMEM;
extern const uint16_t pagumon_walkback_1[] PROGMEM;
extern const uint16_t pagumon_walkback_2[] PROGMEM;

extern const uint16_t* const pagumon_attack_frames[5];
extern const uint16_t* const pagumon_happy_frames[3];
extern const uint16_t* const pagumon_walk_frames[3];
extern const uint16_t* const pagumon_walkback_frames[3];

#endif
