// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Palmon   action size: 40px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef PALMON_SPRITES_H
#define PALMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define PALMON_SPRITE_SIZE   40
#define PALMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define PALMON_ATTACK_W      44
#define PALMON_ATTACK_H      48

extern const uint16_t palmon_attack_0[] PROGMEM;
extern const uint16_t palmon_attack_1[] PROGMEM;
extern const uint16_t palmon_attack_2[] PROGMEM;
extern const uint16_t palmon_happy_0[] PROGMEM;
extern const uint16_t palmon_happy_1[] PROGMEM;
extern const uint16_t palmon_happy_2[] PROGMEM;
extern const uint16_t palmon_profile[] PROGMEM;
extern const uint16_t palmon_walk_0[] PROGMEM;
extern const uint16_t palmon_walk_1[] PROGMEM;
extern const uint16_t palmon_walk_2[] PROGMEM;
extern const uint16_t palmon_walkback_0[] PROGMEM;
extern const uint16_t palmon_walkback_1[] PROGMEM;
extern const uint16_t palmon_walkback_2[] PROGMEM;

extern const uint16_t* const palmon_attack_frames[3];
extern const uint16_t* const palmon_happy_frames[3];
extern const uint16_t* const palmon_walk_frames[3];
extern const uint16_t* const palmon_walkback_frames[3];

#endif
