// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: pandamon   action size: 40px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef PANDAMON_SPRITES_H
#define PANDAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define PANDAMON_SPRITE_SIZE   40
#define PANDAMON_PROFILE_SIZE  30

extern const uint16_t pandamon_happy_0[] PROGMEM;
extern const uint16_t pandamon_happy_1[] PROGMEM;
extern const uint16_t pandamon_happy_2[] PROGMEM;
extern const uint16_t pandamon_idle[] PROGMEM;
extern const uint16_t pandamon_profile[] PROGMEM;

extern const uint16_t* const pandamon_happy_frames[3];

#endif
