// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Patamon   action size: 33px (auto (normal poses + pad, clamped to [16,64]))   profile size: 26px (auto (native))   pad: 0.12
#ifndef PATAMON_SPRITES_H
#define PATAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define PATAMON_SPRITE_SIZE   33
#define PATAMON_PROFILE_SIZE  26
// Attack frames use their OWN box (bigger than the pose square).
#define PATAMON_ATTACK_W      48
#define PATAMON_ATTACK_H      39

extern const uint16_t patamon_attack_0[] PROGMEM;
extern const uint16_t patamon_attack_1[] PROGMEM;
extern const uint16_t patamon_attack_2[] PROGMEM;
extern const uint16_t patamon_attack_3[] PROGMEM;
extern const uint16_t patamon_happy_0[] PROGMEM;
extern const uint16_t patamon_happy_1[] PROGMEM;
extern const uint16_t patamon_happy_2[] PROGMEM;
extern const uint16_t patamon_profile[] PROGMEM;
extern const uint16_t patamon_walk_0[] PROGMEM;
extern const uint16_t patamon_walk_1[] PROGMEM;
extern const uint16_t patamon_walk_2[] PROGMEM;
extern const uint16_t patamon_walkback_0[] PROGMEM;
extern const uint16_t patamon_walkback_1[] PROGMEM;
extern const uint16_t patamon_walkback_2[] PROGMEM;

extern const uint16_t* const patamon_attack_frames[4];
extern const uint16_t* const patamon_happy_frames[3];
extern const uint16_t* const patamon_walk_frames[3];
extern const uint16_t* const patamon_walkback_frames[3];

#endif
