// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: PawnChessmon White   action size: 41px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef PAWNCHESSMON_WHITE_SPRITES_H
#define PAWNCHESSMON_WHITE_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define PAWNCHESSMON_WHITE_SPRITE_SIZE   41
#define PAWNCHESSMON_WHITE_PROFILE_SIZE  30
// Attack frames use their OWN box (bigger than the pose square).
#define PAWNCHESSMON_WHITE_ATTACK_W      36
#define PAWNCHESSMON_WHITE_ATTACK_H      48

extern const uint16_t pawnchessmon_white_attack_0[] PROGMEM;
extern const uint16_t pawnchessmon_white_attack_1[] PROGMEM;
extern const uint16_t pawnchessmon_white_attack_2[] PROGMEM;
extern const uint16_t pawnchessmon_white_happy_0[] PROGMEM;
extern const uint16_t pawnchessmon_white_happy_1[] PROGMEM;
extern const uint16_t pawnchessmon_white_happy_2[] PROGMEM;
extern const uint16_t pawnchessmon_white_profile[] PROGMEM;
extern const uint16_t pawnchessmon_white_walk_0[] PROGMEM;
extern const uint16_t pawnchessmon_white_walk_1[] PROGMEM;
extern const uint16_t pawnchessmon_white_walk_2[] PROGMEM;
extern const uint16_t pawnchessmon_white_walkback_0[] PROGMEM;
extern const uint16_t pawnchessmon_white_walkback_1[] PROGMEM;
extern const uint16_t pawnchessmon_white_walkback_2[] PROGMEM;

extern const uint16_t* const pawnchessmon_white_attack_frames[3];
extern const uint16_t* const pawnchessmon_white_happy_frames[3];
extern const uint16_t* const pawnchessmon_white_walk_frames[3];
extern const uint16_t* const pawnchessmon_white_walkback_frames[3];

#endif
