// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: PawnChessmonBlack   action size: 41px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef PAWNCHESSMONBLACK_SPRITES_H
#define PAWNCHESSMONBLACK_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define PAWNCHESSMONBLACK_SPRITE_SIZE   41
#define PAWNCHESSMONBLACK_PROFILE_SIZE  30
// Attack frames use their OWN box (bigger than the pose square).
#define PAWNCHESSMONBLACK_ATTACK_W      36
#define PAWNCHESSMONBLACK_ATTACK_H      48

extern const uint16_t pawnchessmonblack_attack_0[] PROGMEM;
extern const uint16_t pawnchessmonblack_attack_1[] PROGMEM;
extern const uint16_t pawnchessmonblack_attack_2[] PROGMEM;
extern const uint16_t pawnchessmonblack_happy_0[] PROGMEM;
extern const uint16_t pawnchessmonblack_happy_1[] PROGMEM;
extern const uint16_t pawnchessmonblack_happy_2[] PROGMEM;
extern const uint16_t pawnchessmonblack_profile[] PROGMEM;
extern const uint16_t pawnchessmonblack_walk_0[] PROGMEM;
extern const uint16_t pawnchessmonblack_walk_1[] PROGMEM;
extern const uint16_t pawnchessmonblack_walk_2[] PROGMEM;
extern const uint16_t pawnchessmonblack_walkback_0[] PROGMEM;
extern const uint16_t pawnchessmonblack_walkback_1[] PROGMEM;
extern const uint16_t pawnchessmonblack_walkback_2[] PROGMEM;

extern const uint16_t* const pawnchessmonblack_attack_frames[3];
extern const uint16_t* const pawnchessmonblack_happy_frames[3];
extern const uint16_t* const pawnchessmonblack_walk_frames[3];
extern const uint16_t* const pawnchessmonblack_walkback_frames[3];

#endif
