// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Penguinmon   action size: 39px (auto (normal poses + pad, clamped to [16,64]))   profile size: 27px (auto (native))   pad: 0.12
#ifndef PENGUINMON_SPRITES_H
#define PENGUINMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define PENGUINMON_SPRITE_SIZE   39
#define PENGUINMON_PROFILE_SIZE  27
// Attack frames use their OWN box (bigger than the pose square).
#define PENGUINMON_ATTACK_W      48
#define PENGUINMON_ATTACK_H      44

extern const uint16_t penguinmon_attack_0[] PROGMEM;
extern const uint16_t penguinmon_attack_1[] PROGMEM;
extern const uint16_t penguinmon_attack_2[] PROGMEM;
extern const uint16_t penguinmon_happy_0[] PROGMEM;
extern const uint16_t penguinmon_happy_1[] PROGMEM;
extern const uint16_t penguinmon_happy_2[] PROGMEM;
extern const uint16_t penguinmon_profile[] PROGMEM;
extern const uint16_t penguinmon_walk_0[] PROGMEM;
extern const uint16_t penguinmon_walk_1[] PROGMEM;
extern const uint16_t penguinmon_walk_2[] PROGMEM;
extern const uint16_t penguinmon_walkback_0[] PROGMEM;
extern const uint16_t penguinmon_walkback_1[] PROGMEM;
extern const uint16_t penguinmon_walkback_2[] PROGMEM;

extern const uint16_t* const penguinmon_attack_frames[3];
extern const uint16_t* const penguinmon_happy_frames[3];
extern const uint16_t* const penguinmon_walk_frames[3];
extern const uint16_t* const penguinmon_walkback_frames[3];

#endif
