// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Renamon   action size: 48px (auto (normal poses + pad, clamped to [16,64]))   profile size: 30px (auto (native))   pad: 0.12
#ifndef RENAMON_SPRITES_H
#define RENAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define RENAMON_SPRITE_SIZE   48
#define RENAMON_PROFILE_SIZE  30
// Attack frames use their OWN box (bigger than the pose square).
#define RENAMON_ATTACK_W      39
#define RENAMON_ATTACK_H      48

extern const uint16_t renamon_attack_0[] PROGMEM;
extern const uint16_t renamon_attack_1[] PROGMEM;
extern const uint16_t renamon_attack_2[] PROGMEM;
extern const uint16_t renamon_happy_0[] PROGMEM;
extern const uint16_t renamon_happy_1[] PROGMEM;
extern const uint16_t renamon_happy_2[] PROGMEM;
extern const uint16_t renamon_profile[] PROGMEM;
extern const uint16_t renamon_walk_0[] PROGMEM;
extern const uint16_t renamon_walk_1[] PROGMEM;
extern const uint16_t renamon_walk_2[] PROGMEM;
extern const uint16_t renamon_walkback_0[] PROGMEM;
extern const uint16_t renamon_walkback_1[] PROGMEM;
extern const uint16_t renamon_walkback_2[] PROGMEM;

extern const uint16_t* const renamon_attack_frames[3];
extern const uint16_t* const renamon_happy_frames[3];
extern const uint16_t* const renamon_walk_frames[3];
extern const uint16_t* const renamon_walkback_frames[3];

#endif
