// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Salamon   action size: 32px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef SALAMON_SPRITES_H
#define SALAMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define SALAMON_SPRITE_SIZE   32
#define SALAMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define SALAMON_ATTACK_W      36
#define SALAMON_ATTACK_H      42

extern const uint16_t salamon_attack_0[] PROGMEM;
extern const uint16_t salamon_attack_1[] PROGMEM;
extern const uint16_t salamon_attack_2[] PROGMEM;
extern const uint16_t salamon_happy_0[] PROGMEM;
extern const uint16_t salamon_happy_1[] PROGMEM;
extern const uint16_t salamon_happy_2[] PROGMEM;
extern const uint16_t salamon_profile[] PROGMEM;
extern const uint16_t salamon_walk_0[] PROGMEM;
extern const uint16_t salamon_walk_1[] PROGMEM;
extern const uint16_t salamon_walk_2[] PROGMEM;
extern const uint16_t salamon_walkback_0[] PROGMEM;
extern const uint16_t salamon_walkback_1[] PROGMEM;
extern const uint16_t salamon_walkback_2[] PROGMEM;

extern const uint16_t* const salamon_attack_frames[3];
extern const uint16_t* const salamon_happy_frames[3];
extern const uint16_t* const salamon_walk_frames[3];
extern const uint16_t* const salamon_walkback_frames[3];

#endif
