// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: ShadowToyAgumon   action size: 40px (auto (normal poses + pad, clamped to [16,64]))   profile size: 29px (auto (native))   pad: 0.12
#ifndef SHADOWTOYAGUMON_SPRITES_H
#define SHADOWTOYAGUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define SHADOWTOYAGUMON_SPRITE_SIZE   40
#define SHADOWTOYAGUMON_PROFILE_SIZE  29
// Attack frames use their OWN box (bigger than the pose square).
#define SHADOWTOYAGUMON_ATTACK_W      40
#define SHADOWTOYAGUMON_ATTACK_H      48

extern const uint16_t shadowtoyagumon_attack_0[] PROGMEM;
extern const uint16_t shadowtoyagumon_attack_1[] PROGMEM;
extern const uint16_t shadowtoyagumon_attack_2[] PROGMEM;
extern const uint16_t shadowtoyagumon_happy_0[] PROGMEM;
extern const uint16_t shadowtoyagumon_happy_1[] PROGMEM;
extern const uint16_t shadowtoyagumon_happy_2[] PROGMEM;
extern const uint16_t shadowtoyagumon_profile[] PROGMEM;
extern const uint16_t shadowtoyagumon_walk_0[] PROGMEM;
extern const uint16_t shadowtoyagumon_walk_1[] PROGMEM;
extern const uint16_t shadowtoyagumon_walk_2[] PROGMEM;
extern const uint16_t shadowtoyagumon_walkback_0[] PROGMEM;
extern const uint16_t shadowtoyagumon_walkback_1[] PROGMEM;
extern const uint16_t shadowtoyagumon_walkback_2[] PROGMEM;

extern const uint16_t* const shadowtoyagumon_attack_frames[3];
extern const uint16_t* const shadowtoyagumon_happy_frames[3];
extern const uint16_t* const shadowtoyagumon_walk_frames[3];
extern const uint16_t* const shadowtoyagumon_walkback_frames[3];

#endif
