// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: SnowAgumon   action size: 36px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef SNOWAGUMON_SPRITES_H
#define SNOWAGUMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define SNOWAGUMON_SPRITE_SIZE   36
#define SNOWAGUMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define SNOWAGUMON_ATTACK_W      48
#define SNOWAGUMON_ATTACK_H      48

extern const uint16_t snowagumon_attack_0[] PROGMEM;
extern const uint16_t snowagumon_attack_1[] PROGMEM;
extern const uint16_t snowagumon_attack_2[] PROGMEM;
extern const uint16_t snowagumon_happy_0[] PROGMEM;
extern const uint16_t snowagumon_happy_1[] PROGMEM;
extern const uint16_t snowagumon_happy_2[] PROGMEM;
extern const uint16_t snowagumon_profile[] PROGMEM;
extern const uint16_t snowagumon_walk_0[] PROGMEM;
extern const uint16_t snowagumon_walk_1[] PROGMEM;
extern const uint16_t snowagumon_walk_2[] PROGMEM;
extern const uint16_t snowagumon_walkback_0[] PROGMEM;
extern const uint16_t snowagumon_walkback_1[] PROGMEM;
extern const uint16_t snowagumon_walkback_2[] PROGMEM;

extern const uint16_t* const snowagumon_attack_frames[3];
extern const uint16_t* const snowagumon_happy_frames[3];
extern const uint16_t* const snowagumon_walk_frames[3];
extern const uint16_t* const snowagumon_walkback_frames[3];

#endif
