// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: tanemon   action size: 42px (auto-derived (clamped to [32,56]))   profile size: 30px   pad: 0.12
#ifndef TANEMON_SPRITES_H
#define TANEMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define TANEMON_SPRITE_SIZE   42
#define TANEMON_PROFILE_SIZE  30

extern const uint16_t tanemon_attack_0[] PROGMEM;
extern const uint16_t tanemon_attack_1[] PROGMEM;
extern const uint16_t tanemon_attack_2[] PROGMEM;
extern const uint16_t tanemon_attack_3[] PROGMEM;
extern const uint16_t tanemon_attack_4[] PROGMEM;
extern const uint16_t tanemon_happy_0[] PROGMEM;
extern const uint16_t tanemon_happy_1[] PROGMEM;
extern const uint16_t tanemon_happy_2[] PROGMEM;
extern const uint16_t tanemon_profile[] PROGMEM;
extern const uint16_t tanemon_walk_0[] PROGMEM;
extern const uint16_t tanemon_walk_1[] PROGMEM;
extern const uint16_t tanemon_walk_2[] PROGMEM;
extern const uint16_t tanemon_walkback_0[] PROGMEM;
extern const uint16_t tanemon_walkback_1[] PROGMEM;
extern const uint16_t tanemon_walkback_2[] PROGMEM;

extern const uint16_t* const tanemon_attack_frames[5];
extern const uint16_t* const tanemon_happy_frames[3];
extern const uint16_t* const tanemon_walk_frames[3];
extern const uint16_t* const tanemon_walkback_frames[3];

#endif
