// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Tapirmon   action size: 37px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef TAPIRMON_SPRITES_H
#define TAPIRMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define TAPIRMON_SPRITE_SIZE   37
#define TAPIRMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define TAPIRMON_ATTACK_W      47
#define TAPIRMON_ATTACK_H      48

extern const uint16_t tapirmon_attack_0[] PROGMEM;
extern const uint16_t tapirmon_attack_1[] PROGMEM;
extern const uint16_t tapirmon_attack_2[] PROGMEM;
extern const uint16_t tapirmon_happy_0[] PROGMEM;
extern const uint16_t tapirmon_happy_1[] PROGMEM;
extern const uint16_t tapirmon_happy_2[] PROGMEM;
extern const uint16_t tapirmon_profile[] PROGMEM;
extern const uint16_t tapirmon_walk_0[] PROGMEM;
extern const uint16_t tapirmon_walk_1[] PROGMEM;
extern const uint16_t tapirmon_walk_2[] PROGMEM;
extern const uint16_t tapirmon_walkback_0[] PROGMEM;
extern const uint16_t tapirmon_walkback_1[] PROGMEM;
extern const uint16_t tapirmon_walkback_2[] PROGMEM;

extern const uint16_t* const tapirmon_attack_frames[3];
extern const uint16_t* const tapirmon_happy_frames[3];
extern const uint16_t* const tapirmon_walk_frames[3];
extern const uint16_t* const tapirmon_walkback_frames[3];

#endif
