// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Tentomon   action size: 36px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef TENTOMON_SPRITES_H
#define TENTOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define TENTOMON_SPRITE_SIZE   36
#define TENTOMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define TENTOMON_ATTACK_W      48
#define TENTOMON_ATTACK_H      48

extern const uint16_t tentomon_attack_0[] PROGMEM;
extern const uint16_t tentomon_attack_1[] PROGMEM;
extern const uint16_t tentomon_attack_2[] PROGMEM;
extern const uint16_t tentomon_happy_0[] PROGMEM;
extern const uint16_t tentomon_happy_1[] PROGMEM;
extern const uint16_t tentomon_happy_2[] PROGMEM;
extern const uint16_t tentomon_profile[] PROGMEM;
extern const uint16_t tentomon_walk_0[] PROGMEM;
extern const uint16_t tentomon_walk_1[] PROGMEM;
extern const uint16_t tentomon_walk_2[] PROGMEM;
extern const uint16_t tentomon_walkback_0[] PROGMEM;
extern const uint16_t tentomon_walkback_1[] PROGMEM;
extern const uint16_t tentomon_walkback_2[] PROGMEM;

extern const uint16_t* const tentomon_attack_frames[3];
extern const uint16_t* const tentomon_happy_frames[3];
extern const uint16_t* const tentomon_walk_frames[3];
extern const uint16_t* const tentomon_walkback_frames[3];

#endif
