// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: terriermon   action size: 41px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef TERRIERMON_SPRITES_H
#define TERRIERMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define TERRIERMON_SPRITE_SIZE   41
#define TERRIERMON_PROFILE_SIZE  30

extern const uint16_t terriermon_attack_0[] PROGMEM;
extern const uint16_t terriermon_attack_1[] PROGMEM;
extern const uint16_t terriermon_happy_0[] PROGMEM;
extern const uint16_t terriermon_happy_1[] PROGMEM;
extern const uint16_t terriermon_happy_2[] PROGMEM;
extern const uint16_t terriermon_profile[] PROGMEM;
extern const uint16_t terriermon_sleep[] PROGMEM;
extern const uint16_t terriermon_walk_0[] PROGMEM;
extern const uint16_t terriermon_walk_1[] PROGMEM;
extern const uint16_t terriermon_walk_2[] PROGMEM;
extern const uint16_t terriermon_walkback_0[] PROGMEM;
extern const uint16_t terriermon_walkback_1[] PROGMEM;
extern const uint16_t terriermon_walkback_2[] PROGMEM;

extern const uint16_t* const terriermon_attack_frames[2];
extern const uint16_t* const terriermon_happy_frames[3];
extern const uint16_t* const terriermon_walk_frames[3];
extern const uint16_t* const terriermon_walkback_frames[3];

#endif
