// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: tokomon   action size: 49px (auto-derived (clamped to [32,56]))   profile size: 30px   pad: 0.12
#ifndef TOKOMON_SPRITES_H
#define TOKOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define TOKOMON_SPRITE_SIZE   49
#define TOKOMON_PROFILE_SIZE  30

extern const uint16_t tokomon_attack_0[] PROGMEM;
extern const uint16_t tokomon_attack_1[] PROGMEM;
extern const uint16_t tokomon_attack_2[] PROGMEM;
extern const uint16_t tokomon_happy_0[] PROGMEM;
extern const uint16_t tokomon_happy_1[] PROGMEM;
extern const uint16_t tokomon_happy_2[] PROGMEM;
extern const uint16_t tokomon_profile[] PROGMEM;
extern const uint16_t tokomon_walk_0[] PROGMEM;
extern const uint16_t tokomon_walk_1[] PROGMEM;
extern const uint16_t tokomon_walk_2[] PROGMEM;
extern const uint16_t tokomon_walkback_0[] PROGMEM;
extern const uint16_t tokomon_walkback_1[] PROGMEM;
extern const uint16_t tokomon_walkback_2[] PROGMEM;

extern const uint16_t* const tokomon_attack_frames[3];
extern const uint16_t* const tokomon_happy_frames[3];
extern const uint16_t* const tokomon_walk_frames[3];
extern const uint16_t* const tokomon_walkback_frames[3];

#endif
