// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: tsunomon   action size: 20px (forced via --size)   profile size: 30px   pad: 0.12
#ifndef TSUNOMON_SPRITES_H
#define TSUNOMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define TSUNOMON_SPRITE_SIZE   20
#define TSUNOMON_PROFILE_SIZE  30

extern const uint16_t tsunomon_attack_0[] PROGMEM;
extern const uint16_t tsunomon_attack_1[] PROGMEM;
extern const uint16_t tsunomon_attack_2[] PROGMEM;
extern const uint16_t tsunomon_attack_3[] PROGMEM;
extern const uint16_t tsunomon_happy_0[] PROGMEM;
extern const uint16_t tsunomon_happy_1[] PROGMEM;
extern const uint16_t tsunomon_happy_2[] PROGMEM;
extern const uint16_t tsunomon_profile[] PROGMEM;
extern const uint16_t tsunomon_walk_0[] PROGMEM;
extern const uint16_t tsunomon_walk_1[] PROGMEM;
extern const uint16_t tsunomon_walk_2[] PROGMEM;
extern const uint16_t tsunomon_walkback_0[] PROGMEM;
extern const uint16_t tsunomon_walkback_1[] PROGMEM;
extern const uint16_t tsunomon_walkback_2[] PROGMEM;

extern const uint16_t* const tsunomon_attack_frames[4];
extern const uint16_t* const tsunomon_happy_frames[3];
extern const uint16_t* const tsunomon_walk_frames[3];
extern const uint16_t* const tsunomon_walkback_frames[3];

#endif
