// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Veemon   action size: 41px (auto (normal poses + pad, clamped to [16,64]))   profile size: 28px (auto (native))   pad: 0.12
#ifndef VEEMON_SPRITES_H
#define VEEMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define VEEMON_SPRITE_SIZE   41
#define VEEMON_PROFILE_SIZE  28
// Attack frames use their OWN box (bigger than the pose square).
#define VEEMON_ATTACK_W      36
#define VEEMON_ATTACK_H      48

extern const uint16_t veemon_attack_0[] PROGMEM;
extern const uint16_t veemon_attack_1[] PROGMEM;
extern const uint16_t veemon_attack_2[] PROGMEM;
extern const uint16_t veemon_happy_0[] PROGMEM;
extern const uint16_t veemon_happy_1[] PROGMEM;
extern const uint16_t veemon_happy_2[] PROGMEM;
extern const uint16_t veemon_profile[] PROGMEM;
extern const uint16_t veemon_walk_0[] PROGMEM;
extern const uint16_t veemon_walk_1[] PROGMEM;
extern const uint16_t veemon_walk_2[] PROGMEM;
extern const uint16_t veemon_walkback_0[] PROGMEM;
extern const uint16_t veemon_walkback_1[] PROGMEM;
extern const uint16_t veemon_walkback_2[] PROGMEM;

extern const uint16_t* const veemon_attack_frames[3];
extern const uint16_t* const veemon_happy_frames[3];
extern const uint16_t* const veemon_walk_frames[3];
extern const uint16_t* const veemon_walkback_frames[3];

#endif
