// AUTO-GENERATED by tools/build_digimon_sprites.py -- do not edit by hand.
// Digimon: Wormmon   action size: 43px (auto (normal poses + pad, clamped to [16,64]))   profile size: 27px (auto (native))   pad: 0.12
#ifndef WORMMON_SPRITES_H
#define WORMMON_SPRITES_H

#include <Arduino.h>

// Uniform on-screen square size for this Digimon's action sprites.
#define WORMMON_SPRITE_SIZE   43
#define WORMMON_PROFILE_SIZE  27
// Attack frames use their OWN box (bigger than the pose square).
#define WORMMON_ATTACK_W      48
#define WORMMON_ATTACK_H      31

extern const uint16_t wormmon_attack_0[] PROGMEM;
extern const uint16_t wormmon_attack_1[] PROGMEM;
extern const uint16_t wormmon_attack_2[] PROGMEM;
extern const uint16_t wormmon_happy_0[] PROGMEM;
extern const uint16_t wormmon_happy_1[] PROGMEM;
extern const uint16_t wormmon_happy_2[] PROGMEM;
extern const uint16_t wormmon_profile[] PROGMEM;
extern const uint16_t wormmon_walk_0[] PROGMEM;
extern const uint16_t wormmon_walk_1[] PROGMEM;
extern const uint16_t wormmon_walk_2[] PROGMEM;
extern const uint16_t wormmon_walkback_0[] PROGMEM;
extern const uint16_t wormmon_walkback_1[] PROGMEM;
extern const uint16_t wormmon_walkback_2[] PROGMEM;

extern const uint16_t* const wormmon_attack_frames[3];
extern const uint16_t* const wormmon_happy_frames[3];
extern const uint16_t* const wormmon_walk_frames[3];
extern const uint16_t* const wormmon_walkback_frames[3];

#endif
